### ISSUE TITLE
Camera Preview is upside-down

### ISSUE THREAD

**Issue by apastel** [abbyysdk/RTR-SDK.Android#1]
The camera preview in the sample app is upside-down & backwards on my Nexus 5X. This is a known issue with Nexus 5X devices since the camera orientation is different on this phone. 

Using some code from [developer.android.com](https://developer.android.com/reference/android/hardware/Camera.html#setDisplayOrientation%28int%29) I was able to flip the orientation so that the preview is correct. However, the image is still processed as if it were still flipped.

![screenshot_20170402-165706](https://cloud.githubusercontent.com/assets/8836343/24592113/98eff9c6-17c5-11e7-8932-9e378ac33579.png)

I've been trying to figure out how to flip not just the preview orientation, but the actual image that gets processed by ABBYY. Any ideas? I tried doing `parameters.setRotation()` and passing in the same integer that was passed into `camera.setDisplayOrientation( rotation )` but that didn't work.

**Comment by aleksey-ka** [comment]
Ultimately, the **orientation** of the image is specified in ITextRecognitionService.start method:

 `void start( int width, int height, int orientation, Rect areaOfInterest ) `

The orientation is specified in degrees and should be a multiple of 90. The idea is that the RAW image from the camera is never rotated but the rotation of the scene is given instead.

In the sample, below is the right place for you to change the behavior. Here we initialize the **orientation** field (which later goes in the **start** method) as a function of display rotation. In your case the relation is different:
```
private void configureCameraAndStartPreview( Camera camera )
	{
		// Configure camera orientation. This is needed for both correct preview orientation
		// and recognition

		Display display = getWindowManager().getDefaultDisplay();
		switch( display.getRotation() ) {
			case Surface.ROTATION_0:
				orientation = 90;
				break;
			case Surface.ROTATION_90:
				orientation = 0;
				break;
			case Surface.ROTATION_180:
				orientation = 270;
				break;
			case Surface.ROTATION_270:
				orientation = 180;
				break;
		}
		camera.setDisplayOrientation( orientation );
```
