### ISSUE TITLE
Wrong result scanning number, areacode or part id

### ISSUE THREAD

**Issue by ziselos** [abbyysdk/RTR-SDK.Android#10]
I am using the sample code in order to scan and recognize numbers, area code or part id.
I use the front camera of my phone. Should i make changes in sample code in order to get correct results? The only change i made in sample code is openning the front camera.
Some examples 
![img_0551](https://user-images.githubusercontent.com/16279880/38608450-093d57ac-3d84-11e8-9b59-bf260b05cdf1.JPG)
![img_0555](https://user-images.githubusercontent.com/16279880/38608473-21bedc1a-3d84-11e8-81c0-3116dce3028b.JPG)
![img_0557](https://user-images.githubusercontent.com/16279880/38608519-43dae442-3d84-11e8-9947-290c21f895f9.JPG)
![img_0562](https://user-images.githubusercontent.com/16279880/38608551-5cc3dc98-3d84-11e8-91a8-996fda0f4d01.JPG)

**Comment by aleksey-ka** [comment]
Thank you for the details! 

It looks like you are trying to recognize a **mirrored** image (around horizontal axis): 32 looks like 35 and 15 looks like 12 :)

**Comment by ziselos** [comment]
Yes, i am using a mirror as you can see, because i want to use the front camera of my phone. Is there a way that i can fix it? Using back camera gives me the correct results

**Comment by aleksey-ka** [comment]
You can programmatically mirror the NV21 image around horizontal axis after you get the buffer from the camera and before you pass it to the service. It should not be very hard. See [this](https://stackoverflow.com/questions/33542708/camera2-api-convert-yuv420-to-rgb-green-out/33543885). Just keep in mind that the service expects that you give back the same buffer that was given to you in the onRequestLatestFrame call - you should fill this buffer with the mirrored image.

**Comment by ziselos** [comment]
Thanks. I wiil check the example and i will inform you about the results.

**Comment by aleksey-ka** [comment]
NB. In your case the image is flipped around horizontal axis not because it is the front camera, but rather because you are using a mirror before the lens. What you see in the preview is not the real image which corresponds to NV21 and which is passed to the service

**Comment by ziselos** [comment]
I made a method that rotates the buffer of image. If i understood correct, i should call this method in the onPreviewFrame in order the rotated image to be sent back in the Data service? Something like that:

 ```
private Camera.PreviewCallback cameraPreviewCallback = new Camera.PreviewCallback() {
        @Override
        public void onPreviewFrame(byte[] data, Camera camera) {
            // The buffer that we have given to the camera in IDataCaptureService.Callback.onRequestLatestFrame
            // above have been filled. Send it back to the Data Capture Service
            data = rotateMethod();
            dataCaptureService.submitRequestedFrame(data);
        }
    };
```

**Comment by aleksey-ka** [comment]
Yes. It is the right place to do it.

**Comment by ziselos** [comment]
Thanks. I will test it to see if it works.

**Comment by ziselos** [comment]
Hello, i would like your help on my code below. I debugged your sample-datacapture code and i show that in the service you are passing the data (on onPreviewFrame callback) like this:
![sampleimage](https://user-images.githubusercontent.com/16279880/41821931-a2943e60-77f0-11e8-9641-46a249de22a3.png)
As i said you before, i am using a mirror in the front camera. In order to succeed the same result and pass to the service an image in the same format like you, i wrote the code below that i run on a separate thread. I tried on the seperate thread to control the number of frames so i made a class:  


      class ImageProcessThread extends Thread {

        private byte[] data;

        private ImageProcessThread() {

        }

        public synchronized void setData(byte[] data) {
            if (isProcessing()) {
                return;
            }
            this.data = data;
            if (data != null) {
                start();
            }
        }

        private synchronized boolean isProcessing() {
            return this.data != null;
        }

        private synchronized void clearData() {
            this.data = null;
        }

        @Override
        public void run() {
            YuvImage yuvImage = new YuvImage(data, ImageFormat.NV21, cameraPreviewSize.width, cameraPreviewSize.height, null);
            ByteArrayOutputStream os = new ByteArrayOutputStream();
            yuvImage.compressToJpeg(new Rect(0, 0, cameraPreviewSize.width, cameraPreviewSize.height), 100, os);
            byte[] jpegByteArray = os.toByteArray();
            Bitmap bitmap = BitmapFactory.decodeByteArray(jpegByteArray, 0, jpegByteArray.length);

            Matrix matrix = new Matrix();
            matrix.preScale(1.0f, -1.0f);
            Bitmap bOutput = Bitmap.createBitmap(bitmap, 0, 0, bitmap.getWidth(), bitmap.getHeight(), matrix, true);


            Matrix matrix1 = new Matrix();
            matrix.setRotate(-180);
            Bitmap rotatedBitmap = Bitmap.createBitmap(bOutput, 0, 0, bOutput.getWidth(), bOutput.getHeight(), matrix1, true);

            byte[] bytes = getNV21(rotatedBitmap.getWidth(), rotatedBitmap.getHeight(), rotatedBitmap);

            dataCaptureService.submitRequestedFrame(bytes);

            clearData();
        }
    }  


and in onPreviewFrame i call this
`imageProcessThread.setData(data);`

In the getNV21 method i tried to convert the image in NV21 format 


      
        public static byte [] getNV21(int inputWidth, int inputHeight, Bitmap scaled) {

        int [] argb = new int[inputWidth * inputHeight];

        scaled.getPixels(argb, 0, inputWidth, 0, 0, inputWidth, inputHeight);

        byte [] yuv = new byte[inputWidth*inputHeight*3/2];
        encodeYUV420SP(yuv, argb, inputWidth, inputHeight);

        scaled.recycle();

        return yuv;
    }

    static void encodeYUV420SP(byte[] yuv420sp, int[] argb, int width, int height) {
        final int frameSize = width * height;

        int yIndex = 0;
        int uvIndex = frameSize;

        int a, R, G, B, Y, U, V;
        int index = 0;
        for (int j = 0; j < height; j++) {
            for (int i = 0; i < width; i++) {

                a = (argb[index] & 0xff000000) >> 24; // a is not used obviously
                R = (argb[index] & 0xff0000) >> 16;
                G = (argb[index] & 0xff00) >> 8;
                B = (argb[index] & 0xff) >> 0;

                // well known RGB to YUV algorithm
                Y = ( (  66 * R + 129 * G +  25 * B + 128) >> 8) +  16;
                U = ( ( -38 * R -  74 * G + 112 * B + 128) >> 8) + 128;
                V = ( ( 112 * R -  94 * G -  18 * B + 128) >> 8) + 128;

                // NV21 has a plane of Y and interleaved planes of VU each sampled by a factor of 2
                //    meaning for every 4 Y pixels there are 1 V and 1 U.  Note the sampling is every other
                //    pixel AND every other scanline.
                yuv420sp[yIndex++] = (byte) ((Y < 0) ? 0 : ((Y > 255) ? 255 : Y));
                if (j % 2 == 0 && index % 2 == 0) {
                    yuv420sp[uvIndex++] = (byte)((V<0) ? 0 : ((V > 255) ? 255 : V));
                    yuv420sp[uvIndex++] = (byte)((U<0) ? 0 : ((U > 255) ? 255 : U));
                }

                index ++;
            }
        }
    }  


As a result, on debugging i can see that the images are 
bitmap
![imagefrommirror](https://user-images.githubusercontent.com/16279880/41822074-ca08a2d6-77f2-11e8-9a8c-dcd19c7e9aab.png)
boutput
![imagefrommirrorrotated](https://user-images.githubusercontent.com/16279880/41822078-e40b8d4c-77f2-11e8-8039-924487395aa4.png)
and the rotated image, that i pass to the service (like in the sample code) is
![imagefrommirrorsenttoservice](https://user-images.githubusercontent.com/16279880/41822088-02392504-77f3-11e8-818e-fa74cfba5a45.png)

Unfortunately, recognition is not happening. The code is running for a long time (probably for the transformation in NV21 format in getNV1 method). I wonder if is there a way to make the rotation directly in NV21 format without any transformation. What am i missing?

**Comment by aleksey-ka** [comment]
1) We expect that the buffer that is passed to submitRequestedFrame is **the same** buffer that was passed as the argument in the onRequestLatestFrame. If you pass a new buffer - it is just ignored. So you should either rotate the frame from the camera **in-place**. Or copy the rotated frame back to the original buffer.
2) You are right about rotating NV21 buffer without converting it to other formats. The first WIDTH*HEIGHT bytes of the image are just the gray pixels (one byte one pixel and the value is the intensity). It is trivial to rotate these.

Sorry for the long delay with the answer.

**Comment by ziselos** [comment]
Thanks for your response. 
1. I will try to copy the rotated frame back to the original buffer and let you know about the result.
2. About the directly rotation of NV21, i also tried [this](https://stackoverflow.com/questions/51225886/android-yuv420-nv21-image-horizontal-flip-using-reflector-on-front-camera). I tried to flip horizontal the byte array without any transformation. But again i need to copy the flipped buffer back to the original one as you said in 1. I will try it also and let you know. But as you can see i am getting this green background color. Does this affect the recognition process? 

Thanks for helping me.

**Comment by ziselos** [comment]
I tried as you said, to copy the rotated frame back to the original buffer, and the recogition of the number was successful. I tried the second way (flip horizontal the byte array without any transformation). Thanks a lot for your help.
