### ISSUE TITLE
License file copied in Assets folder not found

### ISSUE THREAD

**Issue by rameeznkhan** [abbyysdk/RTR-SDK.Android#14]
I'm trying to integrate the SDK in one of my projects. After successfully integrating the Library, I have copied the AbbyyRtrSdk.license file in the Assets folder but when I call the method
`Engine.load(activity, "/src/main/assets/AbbyyRtrSdk.license")` it causes FileNotFoundException. Should the file be copied somewhere else?

**Comment by IvanShafran** [comment]
Hi!

`Engine.load` accepts relative to the assets directory path.
Correct method call is `Engine.load(activity, "AbbyyRtrSdk.license")`.

Sorry for the long response delay.
I hope you figured the problem out by yourself.

Thank you for your interest in our SDK.
