### ISSUE TITLE
Could you help me for evaluating multiple still-images

### ISSUE THREAD

**Issue by chankyu-choi** [abbyysdk/RTR-SDK.Android#3]
Hi, I wanted to evaluate your OCR-engine accuracy with my some still-images and I tested them on RTR.SDK.Android. This is my test code.

- https://github.com/chankyu-choi/RTR-SDK.Android/blob/master/MainActivity.java

I forced the callback function to work sequentially, but sometimes the result is delayed in one frame.
I also confirmed the previous result was printed when OCR recognition was failed. So, is there a way to initialize the engine so that it is not affected by previous results. This is for multiple stiil images evaluation. Thanks.

**Comment by AlekseyLebedev** [comment]
Hello.

TextCaptureService should be used for the recognition of the text on a video (a series of frames). On switching between different series with different text you have to call stop() and start() method of the service. 

The recognition of still images is a part of the Core API of ABBYY RTR SDK. Here is sample code for still image recognition:
```
IRecognitionCoreAPI recognitionCoreAPI = engine.createRecognitionCoreAPI();
IRecognitionCoreAPI.TextRecognitionCallback callback = new IRecognitionCoreAPI.TextRecognitionCallback() {
	@Override public boolean onProgress( int i, IRecognitionCoreAPI.Warning warning ) { return false; }

	@Override public void onTextOrientationDetected( int i ) { }

	@Override public void onError( Exception e )
	{
		Log.e( TAG, "Recognition error: " + e.getMessage(), e );
	}
};
recognitionCoreAPI.getTextRecognitionSettings().setRecognitionLanguage( Language.English );
IRecognitionCoreAPI.TextBlock[] textBlocks = recognitionCoreAPI.recognizeText( image, callback );
```
Consider to call recognitionCoreAPI.recognizeText (or all this code) from the AsyncTask or on the background thread.

Core API is enabled in the extended version. You should contact our [sales department](http://rtrsdk.com/contacts/) to request a free trial. If you have any technical issues we will be glad to answer them. Also check out this [forum](http://forum.ocrsdk.com/cat/real-time-recognition-sdk/).

Thank you for your interest in our product!
Best regards

**Comment by chankyu-choi** [comment]
Thanks @AlekseyLebedev 
I run the RTR-SDK engine in the way you told me, but I got always return null. (textBlocks have null for all still-images) I don't know what I missed . Could you explain why it happened?

Also, I set setAreaOfInterest function.

`recognitionCoreAPI.getTextRecognitionSettings().setAreaOfInterest(new Rect(0, 0, image.getWidth(), image.getHeight()));`

**Comment by AlekseyLebedev** [comment]
Are there any exceptions in `onError` method?
```
	@Override public void onError( Exception e )
	{
		Log.e( TAG, "Recognition error: " + e.getMessage(), e );
	}
```

**Comment by chankyu-choi** [comment]
There was No Error.

**Comment by AlekseyLebedev** [comment]
Can you send us your code and images?

**Comment by chankyu-choi** [comment]
Sorry, After re-testing, I got the following error : 

<pre><code>
Recognition error:
License not valid or functionality not allowed. License error. Function is not allowed. Current state:
License expires (Day-Month-Year): 31.8.2017.
General availability: Enabled.
Allowed platforms: All.
BCR available: No.
Translation available: Yes.
CJK available: Yes.
Cyrillic available: Yes.
com.abbyy.mobile.rtr.Engine$LicenseException: License not valid or functionality not allowed. License error. Function is not allowed. Current state:
License expires (Day-Month-Year): 31.8.2017.
General availability: Enabled.
Allowed platforms: All.
BCR available: No.
Translation available: Yes.
CJK available: Yes.
Cyrillic available: Yes.
at com.abbyy.mobile.rtr.RecognitionCoreAPI.recognizeText(RecognitionCoreAPI.java:138)
at com.abbyy.mobile.sample.MainActivity.createTextCaptureService(MainActivity.java:425)
at com.abbyy.mobile.sample.MainActivity.onCreate(MainActivity.java:724)
at android.app.Activity.performCreate(Activity.java:6876)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
at android.app.ActivityThread.access$1100(ActivityThread.java:221)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
</code></pre>

code & resource : [https://github.com/chankyu-choi/RTR-SDK.Android](https://github.com/chankyu-choi/RTR-SDK.Android)

**Comment by AlekseyLebedev** [comment]
Your license has expired. You should contact our [sales department](http://rtrsdk.com/contacts/) to solve this issue. Please indicate in your request that you need still-image recognition. It is better to attach your old license.

**Comment by chankyu-choi** [comment]
@AlekseyLebedev Thanks :)
