### ISSUE TITLE
start another activity after data recognition crashes

### ISSUE THREAD

**Issue by ziselos** [abbyysdk/RTR-SDK.Android#6]
After successful data recoignition, i try to start a new activity but crashes. Where should i call method startActivity?

**Comment by AlekseyLebedev** [comment]
Hello.

Please check, that you call `startActivity()` in the UI thread after finished `IRecognitionService.stop()` invocation. 

If you use this sample, you may call `startActivity()`  from the `onPostExecute` methon of AsyncTask, executed in `stopRecognition()` method.

**Comment by ziselos** [comment]
Hello, 
calling startActivity() from the onPostExecute method works like a charm.
Thanks you very much.
