### ISSUE TITLE
How To Configure For Local Languages.

### ISSUE THREAD

**Issue by ArunaMahaGamage** [abbyysdk/RTR-SDK.Android#7]
I need a local language recolonization OCR app.
May i know how to configure for different languages.

eg : Sri Lanka - Sinhala Language
       India - Hindi Language

**Comment by aleksey-ka** [comment]
If you want to localize the UI of your application for different regions, you can search the internet for something like "localize an android application" and this will give you references to lots of tutorials on how to do it as well as the relevant pages in android developers' documentation:
https://developer.android.com/distribute/best-practices/develop/design-for-translation.html
https://developer.android.com/guide/topics/resources/localization.html#managing-strings-for-localization

The sample applications in this repository are not built to be localized out of the box. They are built to be concise and easy to understand. They can be used as a base for your application, but you'll need to address all localization issues yourselves.

If you want to OCR Hindi and Sinhala - unfortunately these languages are not yet supported in our mobile SDKs. You can [contact](https://rtrsdk.com/contacts/ ) us to ask for future support.

Thank you for your interest in our product!
